#!/usr/bin/bash
~/.config/waybar/config2/scripts/tools/dynamic &
while true
do
    # echo ""
    out=$(cat ~/.config/waybar/config2/store/dynamic_out.txt)
    echo "$out"  | jq --unbuffered --compact-output
    # cat ~/.config/hypr/scripts/tools/dynamic_out.txt
    sleep 0.5
done
