swipe:
  4:
    up:
      command: "pamixer --increase 5 && /home/wraient/.config/hypr/scripts/volumecontrol.sh -o i" # volume up, priority threshold
      threshold: 0.00001
    down:
      command: "pamixer --decrease 5 && /home/wraient/.config/hypr/scripts/volumecontrol.sh -o d" # volume down, priority threshold
      threshold: 0.00001
    right:
      command: "playerctl previous --player plasma-browser-integration; playerctl previous --player spotify; playerctl previous --player cider" # previous song spotify, default threshold
      treshold: 2
    left:
      command: "playerctl next --player plasma-browser-integration; playerctl next --player spotify; playerctl next --player cider" # next song spotify, default threshold
      treshold: 2
  # 3:
  #   right:
  #     command: "playerctl previous --player brave" # previous song spotify, default threshold
  #     treshold: 2
  #   left:
  #     command: "playerctl next --player brave" # next song spotify, default threshold
  #     treshold: 2

hold:
  3:
    command: "playerctl play-pause --player brave; playerctl play-pause --player firefox" # pause/play brave
    threshold: 0.5
  4:
    command: "playerctl play-pause --player spotify; playerctl play-pause --player cider" # pause/play spotify / cider
    threshold: 0.5

threshold: # default threshold
  pinch: 0.3
  swipe: 0.4
  hold: 0.1

plugin: # plugin for tap gesture (does not work for some reason)
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true
